import React from 'react';
import { Card } from '@/components/common/Card';
import { Badge } from '@/components/common/Badge';
import { EmptyState } from '@/components/common/EmptyState';
import { BookOpen, Video, Code } from 'lucide-react';

export interface LearningSectionProps {
  onStartDiagnostic: () => void;
}

export const LearningSection: React.FC<LearningSectionProps> = ({ onStartDiagnostic }) => {
  return (
    <div className="space-y-8 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-deep-green/20">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Badge variant="yellow">Format-Matched Resources</Badge>
            <span className="font-mono text-xs text-muted">ML Resource Allocator</span>
          </div>
          <h2 className="text-xl sm:text-2xl font-extrabold text-dark-text">Recommended Learning Objects</h2>
          <p className="text-xs text-muted mt-1">
            Targeted micro-learning content allocated dynamically based on your active prerequisite skill gaps.
          </p>
        </div>
      </div>

      {/* Resource Category Previews */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="p-6 bg-warm-ivory border-deep-green/30 space-y-3">
          <div className="w-10 h-10 rounded-lg bg-dark-green text-yellow flex items-center justify-center font-bold">
            <BookOpen size={20} />
          </div>
          <h3 className="font-bold text-dark-text text-sm">Interactive Micro-Lessons</h3>
          <p className="text-xs text-muted leading-relaxed">
            Concise text summaries and interactive concept breakdowns targeting foundational concepts.
          </p>
        </Card>

        <Card className="p-6 bg-warm-ivory border-deep-green/30 space-y-3">
          <div className="w-10 h-10 rounded-lg bg-dark-green text-yellow flex items-center justify-center font-bold">
            <Video size={20} />
          </div>
          <h3 className="font-bold text-dark-text text-sm">Visual Walkthroughs</h3>
          <p className="text-xs text-muted leading-relaxed">
            Step-by-step visual explanations for complex prerequisite dependencies.
          </p>
        </Card>

        <Card className="p-6 bg-warm-ivory border-deep-green/30 space-y-3">
          <div className="w-10 h-10 rounded-lg bg-dark-green text-yellow flex items-center justify-center font-bold">
            <Code size={20} />
          </div>
          <h3 className="font-bold text-dark-text text-sm">Guided Practice Tasks</h3>
          <p className="text-xs text-muted leading-relaxed">
            Hands-on problem sets configured with adaptive item discrimination parameters.
          </p>
        </Card>
      </div>

      {/* Main Empty State when no real resources returned from API */}
      <EmptyState
        title="No Recommended Learning Objects Available Yet"
        description="Learning resources are automatically generated by the ML Resource Allocator service once active skill gaps are identified during placement assessments."
        actionLabel="Launch Diagnostic Assessment"
        onAction={onStartDiagnostic}
        statusBadge="POST /api/v1/ml/recommend-resources Contract Ready"
      />
    </div>
  );
};
